# Generated by Django 3.2.7 on 2021-12-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(help_text='访问用户的IP地址', max_length=64, verbose_name='访问IP')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='该用户的访问时刻', verbose_name='访问时间')),
                ('url', models.CharField(help_text='该用户访问的URL地址', max_length=64, verbose_name='访问的URL')),
                ('device', models.CharField(help_text='该用户是用什么浏览器访问的', max_length=256, null=True, verbose_name='访问的浏览器')),
                ('platform', models.CharField(help_text='该用户用的是什么操作系统', max_length=256, null=True, verbose_name='访问的系统')),
            ],
            options={
                'verbose_name_plural': '日志',
                'ordering': ['id'],
            },
        ),
    ]
