# Generated by Django 3.2.7 on 2021-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_active',
            field=models.CharField(default='0', max_length=32, verbose_name='用户标识'),
        ),
    ]
