# Generated by Django 3.2.7 on 2021-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_userinfo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='swiper_img/default.jpg', help_text='轮播图的图片', upload_to='swiper_img/', verbose_name='图片')),
                ('title', models.CharField(help_text='图片的标题', max_length=32, verbose_name='标题')),
                ('img_url', models.CharField(help_text='点击图片要跳转的URL地址', max_length=64, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
